# Generated by Django 6.0.1 on 2026-03-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin7', '0001_initial_comprehensive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cin7_line_id', models.CharField(db_index=True, help_text='Cin7 line item ID', max_length=100)),
                ('cin7_sales_order_id', models.CharField(db_index=True, help_text='Cin7 sales order ID', max_length=100)),
                ('cin7_product_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cin7_product_option_id', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='SKU/Product code', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_shipped', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('line_total', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True)),
                ('comments', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('line_type', models.CharField(max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'cin7_sync_salesorderlineitem',
                'ordering': ['cin7_sales_order_id', 'sort_order'],
            },
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='cin7_sync_b_cin7_id_450021_idx',
            old_name='cin7_branch_cin7_id_139299_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='cin7_sync_b_code_035d18_idx',
            old_name='cin7_branch_code_4b533e_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='cin7_sync_b_is_acti_08f2d6_idx',
            old_name='cin7_branch_is_acti_75e5db_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='cin7_sync_p_cin7_id_291265_idx',
            old_name='cin7_produc_cin7_id_4f8ee2_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='cin7_sync_p_style_c_598e68_idx',
            old_name='cin7_produc_style_c_af8137_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='cin7_sync_p_name_19d0cf_idx',
            old_name='cin7_produc_name_e82951_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='cin7_sync_p_brand_afcaa8_idx',
            old_name='cin7_produc_brand_2a8a5c_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='cin7_sync_p_categor_62f877_idx',
            old_name='cin7_produc_categor_4d05f7_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='cin7_sync_p_status_a91e5e_idx',
            old_name='cin7_produc_status_fa3bae_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='cin7_sync_p_last_sy_ce3065_idx',
            old_name='cin7_produc_last_sy_a037bb_idx',
        ),
        migrations.RenameIndex(
            model_name='productcategory',
            new_name='cin7_sync_p_cin7_id_47e048_idx',
            old_name='cin7_produc_cin7_id_1c8a3d_idx',
        ),
        migrations.RenameIndex(
            model_name='productcategory',
            new_name='cin7_sync_p_name_ff5a3b_idx',
            old_name='cin7_produc_name_3e079b_idx',
        ),
        migrations.RenameIndex(
            model_name='productcategory',
            new_name='cin7_sync_p_is_acti_269a4c_idx',
            old_name='cin7_produc_is_acti_82806d_idx',
        ),
        migrations.RenameIndex(
            model_name='productoption',
            new_name='cin7_sync_p_cin7_id_c444d8_idx',
            old_name='cin7_produc_cin7_id_8920fc_idx',
        ),
        migrations.RenameIndex(
            model_name='productoption',
            new_name='cin7_sync_p_code_8fd802_idx',
            old_name='cin7_produc_code_efae5f_idx',
        ),
        migrations.RenameIndex(
            model_name='productoption',
            new_name='cin7_sync_p_barcode_2c65fb_idx',
            old_name='cin7_produc_barcode_bdae22_idx',
        ),
        migrations.RenameIndex(
            model_name='productoption',
            new_name='cin7_sync_p_product_45e68b_idx',
            old_name='cin7_produc_product_acdccf_idx',
        ),
        migrations.RenameIndex(
            model_name='productoption',
            new_name='cin7_sync_p_status_3067b9_idx',
            old_name='cin7_produc_status_5164e9_idx',
        ),
        migrations.RenameIndex(
            model_name='productoption',
            new_name='cin7_sync_p_stock_a_954230_idx',
            old_name='cin7_produc_stock_a_9e97f2_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='cin7_sync_p_cin7_id_114824_idx',
            old_name='cin7_purcha_cin7_id_29f83f_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='cin7_sync_p_referen_aa4162_idx',
            old_name='cin7_purcha_referen_d09005_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='cin7_sync_p_created_0bb7bc_idx',
            old_name='cin7_purcha_created_94a4c7_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='cin7_sync_p_status_d27b1a_idx',
            old_name='cin7_purcha_status_dd96de_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='cin7_sync_p_stage_1d8a34_idx',
            old_name='cin7_purcha_stage_30152e_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='cin7_sync_p_total_751192_idx',
            old_name='cin7_purcha_total_5568fd_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='cin7_sync_p_supplie_7b1756_idx',
            old_name='cin7_purcha_supplie_5f321a_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='cin7_sync_s_cin7_id_0f3304_idx',
            old_name='cin7_saleso_cin7_id_a4d464_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='cin7_sync_s_referen_cb3b36_idx',
            old_name='cin7_saleso_referen_b51359_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='cin7_sync_s_created_39ea19_idx',
            old_name='cin7_saleso_created_583cb4_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='cin7_sync_s_status_9e1d13_idx',
            old_name='cin7_saleso_status_93c301_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='cin7_sync_s_stage_1c4174_idx',
            old_name='cin7_saleso_stage_5363bb_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='cin7_sync_s_total_e0f613_idx',
            old_name='cin7_saleso_total_91e8c8_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='cin7_sync_s_custome_a49b0a_idx',
            old_name='cin7_saleso_custome_bcae9e_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='cin7_sync_s_cin7_pr_1a7524_idx',
            old_name='cin7_stock_cin7_pr_7d4d0e_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='cin7_sync_s_cin7_pr_c2b3d2_idx',
            old_name='cin7_stock_cin7_pr_c1e6c3_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='cin7_sync_s_cin7_br_98b4ff_idx',
            old_name='cin7_stock_cin7_br_bebbf4_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='cin7_sync_s_code_eb7503_idx',
            old_name='cin7_stock_code_fc4bac_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='cin7_sync_s_barcode_36290a_idx',
            old_name='cin7_stock_barcode_429b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='cin7_sync_s_availab_cd24d6_idx',
            old_name='cin7_stock_availab_30e465_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='cin7_sync_s_cin7_pr_186982_idx',
            old_name='cin7_stock_cin7_pr_df1222_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product cost price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name from order', max_length=255),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Invoice date', null=True),
        ),
        migrations.AlterModelTable(
            name='branch',
            table='cin7_sync_branch',
        ),
        migrations.AlterModelTable(
            name='product',
            table='cin7_sync_product',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='cin7_sync_productcategory',
        ),
        migrations.AlterModelTable(
            name='productoption',
            table='cin7_sync_productoption',
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='cin7_sync_purchaseorder',
        ),
        migrations.AlterModelTable(
            name='salesorder',
            table='cin7_sync_salesorder',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='cin7_sync_stock',
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_line_items', to='cin7.product'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='cin7.salesorder'),
        ),
        migrations.AddIndex(
            model_name='salesorderlineitem',
            index=models.Index(fields=['cin7_line_id'], name='cin7_sync_s_cin7_li_951c18_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderlineitem',
            index=models.Index(fields=['cin7_sales_order_id'], name='cin7_sync_s_cin7_sa_bc36a9_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderlineitem',
            index=models.Index(fields=['cin7_product_id'], name='cin7_sync_s_cin7_pr_f733a3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderlineitem',
            index=models.Index(fields=['code'], name='cin7_sync_s_code_96818f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderlineitem',
            index=models.Index(fields=['line_total'], name='cin7_sync_s_line_to_babbbf_idx'),
        ),
    ]
