# Generated by Django 6.0.1 on 2026-03-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin7', '0002_salesorderlineitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Primary category ID', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, db_index=True, help_text="Primary category name (e.g., 'Avondale Shop')", max_length=255),
        ),
    ]
