# Generated by Django 6.0.1 on 2026-03-16 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin7', '0003_product_category_id_product_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product_option',
        ),
        migrations.AddField(
            model_name='stock',
            name='option1',
            field=models.CharField(blank=True, db_column='option1', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='option2',
            field=models.CharField(blank=True, db_column='option2', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='option3',
            field=models.CharField(blank=True, db_column='option3', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='cin7.branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='cin7.product'),
        ),
    ]
