# Generated by Django 6.0.1 on 2026-03-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cin7', '0004_remove_stock_option_1_remove_stock_option_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': False, 'ordering': ['name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False, 'ordering': ['company', 'last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'managed': False, 'ordering': ['product', 'code']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'managed': False, 'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'managed': False, 'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False, 'ordering': ['product_name', 'code', 'branch_name']},
        ),
    ]
