# Generated by Django 6.0.1 on 2026-03-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cin7', '0005_alter_branch_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='cin7_sync_contact',
        ),
    ]
