# Generated by Django 6.0.1 on 2026-02-03 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the role', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the role's purpose and responsibilities")),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='JSON field for flexible permission configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is currently active')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number", max_length=20)),
                ('department', models.CharField(blank=True, help_text="User's department", max_length=100)),
                ('job_title', models.CharField(blank=True, help_text="User's job title", max_length=100)),
                ('bio', models.TextField(blank=True, help_text='User biography or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='user_profiles', to='users.role')),
                ('user', models.OneToOneField(help_text='Associated Django User', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
