# Generated by Django 6.0.1 on 2026-02-03 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, help_text='Unique username for login', max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Unique email address', max_length=254, unique=True)),
                ('password_hash', models.CharField(help_text='Argon2 hashed password', max_length=255)),
                ('first_name', models.CharField(blank=True, help_text="User's first name", max_length=150)),
                ('last_name', models.CharField(blank=True, help_text="User's last name", max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number", max_length=20)),
                ('department', models.CharField(blank=True, help_text="User's department", max_length=100)),
                ('job_title', models.CharField(blank=True, help_text="User's job title", max_length=100)),
                ('bio', models.TextField(blank=True, help_text='User biography or notes')),
                ('is_active', models.BooleanField(default=False, help_text='User account is active (requires email verification)')),
                ('is_staff', models.BooleanField(default=False, help_text='User can access admin interface')),
                ('is_superuser', models.BooleanField(default=False, help_text='User has all permissions')),
                ('email_verified', models.BooleanField(default=False, help_text='Email address has been verified')),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Number of consecutive failed login attempts')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account is locked until this timestamp', null=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful login timestamp', null=True)),
                ('last_password_change', models.DateTimeField(blank=True, help_text='Last password change timestamp', null=True)),
                ('activation_token', models.CharField(blank=True, help_text='Email activation token', max_length=64)),
                ('reset_token', models.CharField(blank=True, help_text='Password reset token', max_length=64)),
                ('reset_token_expires', models.DateTimeField(blank=True, help_text='Password reset token expiration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='custom_users', to='users.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'custom_users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_key', models.CharField(help_text='Unique session identifier', max_length=40, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the session', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Session creation timestamp')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('expires_at', models.DateTimeField(help_text='Session expiration timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Session is currently active')),
                ('remember_me', models.BooleanField(default=False, help_text='Extended session duration (30 days)')),
                ('user', models.ForeignKey(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.customuser')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='custom_user_usernam_134a84_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='custom_user_email_c8f161_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='custom_user_is_acti_f5beb2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email_verified'], name='custom_user_email_v_cb5006_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='user_sessio_expires_66ae96_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='user_sessio_last_ac_7cb421_idx'),
        ),
    ]
