# Generated by Django 6.0.1 on 2026-03-08 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin7', '0003_product_category_id_product_category_name'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, help_text='Assigned branch/shop for store managers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_managers', to='cin7.branch'),
        ),
    ]
