# Generated by Django 6.0.1 on 2026-03-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin7', '0004_remove_stock_option_1_remove_stock_option_2_and_more'),
        ('users', '0004_customuser_assigned_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, help_text='Assigned branches/shops for store managers (can have multiple)', related_name='assigned_managers', to='cin7.branch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_schools',
            field=models.ManyToManyField(blank=True, help_text='Assigned schools for sales team (via Product sub_category)', limit_choices_to={'sub_category__isnull': False}, related_name='assigned_sales_users', to='cin7.product'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use assigned_branches instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_managers_legacy', to='cin7.branch'),
        ),
    ]
