# Generated by Django 6.0.1 on 2026-03-16 05:26

from django.db import migrations


def copy_assigned_branch_to_branches(apps, schema_editor):
    """
    Copy data from old assigned_branch (ForeignKey) to new assigned_branches (ManyToMany).
    This ensures backward compatibility during migration.
    """
    CustomUser = apps.get_model('users', 'CustomUser')

    users_with_branch = CustomUser.objects.filter(assigned_branch__isnull=False)
    count = 0

    for user in users_with_branch:
        # Add the old assigned_branch to the new assigned_branches M2M field
        user.assigned_branches.add(user.assigned_branch)
        count += 1

    print(f'Migrated {count} users with assigned branches')


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Copy first assigned_branches back to assigned_branch.
    Note: This will lose data if users have multiple branches assigned.
    """
    CustomUser = apps.get_model('users', 'CustomUser')

    for user in CustomUser.objects.all():
        if user.assigned_branches.exists():
            # Take the first branch (data loss warning: only keeps one branch)
            user.assigned_branch = user.assigned_branches.first()
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_assigned_branches_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_assigned_branch_to_branches, reverse_migration),
    ]
