# Generated by Django 6.0.1 on 2026-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_store_school_mapping'),
        ('users', '0006_copy_assigned_branch_to_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_stores',
            field=models.ManyToManyField(blank=True, help_text='Stores this user manages (for store-level data access)', related_name='assigned_users', to='dashboard.storeschoolmapping'),
        ),
    ]
