# Generated by Django 6.0.1 on 2026-03-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['cache_key'], name='dashboard_d_cache_k_80159c_idx'), models.Index(fields=['expires_at'], name='dashboard_d_expires_d6f0f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('statistical', 'Statistical Model'), ('ml', 'Machine Learning'), ('hybrid', 'Hybrid (Statistical + ML)')], default='statistical', max_length=20)),
                ('horizon', models.CharField(choices=[('30d', '30 Days'), ('90d', '90 Days'), ('180d', '180 Days'), ('365d', '365 Days')], max_length=10)),
                ('aggregation_level', models.CharField(choices=[('school', 'By School'), ('product', 'By Product'), ('shop', 'By Shop Location'), ('category', 'By Category')], max_length=20)),
                ('entity_name', models.CharField(db_index=True, max_length=255)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('forecast_data', models.JSONField(default=dict)),
                ('forecast_date', models.DateField(db_index=True)),
                ('training_data_start', models.DateField()),
                ('training_data_end', models.DateField()),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('model_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-forecast_date', 'entity_name'],
                'indexes': [models.Index(fields=['forecast_id'], name='dashboard_s_forecas_5531ef_idx'), models.Index(fields=['horizon', 'aggregation_level'], name='dashboard_s_horizon_ad9213_idx'), models.Index(fields=['entity_name', 'forecast_date'], name='dashboard_s_entity__dc19fd_idx'), models.Index(fields=['forecast_date'], name='dashboard_s_forecas_51c640_idx')],
                'unique_together': {('entity_name', 'horizon', 'aggregation_level', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='ForecastAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(db_index=True)),
                ('evaluation_date', models.DateField()),
                ('predicted_quantity', models.FloatField()),
                ('actual_quantity', models.FloatField()),
                ('predicted_revenue', models.FloatField(blank=True, null=True)),
                ('actual_revenue', models.FloatField(blank=True, null=True)),
                ('absolute_error', models.FloatField()),
                ('percentage_error', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_records', to='dashboard.salesforecast')),
            ],
            options={
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['forecast', 'prediction_date'], name='dashboard_f_forecas_df166b_idx'), models.Index(fields=['evaluation_date'], name='dashboard_f_evaluat_e9b5a7_idx')],
                'unique_together': {('forecast', 'prediction_date')},
            },
        ),
    ]
