# Generated by Django 6.0.1 on 2026-03-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin7', '0002_salesorderlineitem_and_more'),
        ('dashboard', '0001_initial'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('supplier_name', models.CharField(db_index=True, max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent_to_supplier', 'Sent to Supplier'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('total_items', models.IntegerField(default=0)),
                ('total_quantity', models.FloatField(default=0)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to='users.customuser')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to='users.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('week_number', models.IntegerField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('school_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('current_stock', models.FloatField()),
                ('forecasted_demand_30d', models.FloatField()),
                ('stock_gap', models.FloatField()),
                ('suggested_quantity', models.FloatField()),
                ('urgency', models.CharField(choices=[('low', 'Low - 30+ days stock'), ('medium', 'Medium - 15-30 days stock'), ('high', 'High - 7-15 days stock'), ('critical', 'Critical - <7 days stock')], default='medium', max_length=20)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending Store Manager Review'), ('approved', 'Approved by Store Manager'), ('modified', 'Modified by Store Manager'), ('rejected', 'Rejected by Store Manager'), ('dp_review', 'Under DP Team Review'), ('dp_approved', 'Approved by DP Team'), ('dp_rejected', 'Rejected by DP Team'), ('po_created', 'PO Created'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('store_approved_quantity', models.FloatField(blank=True, null=True)),
                ('store_manager_comment', models.TextField(blank=True)),
                ('store_approved_at', models.DateTimeField(blank=True, null=True)),
                ('dp_approved_quantity', models.FloatField(blank=True, null=True)),
                ('dp_team_comment', models.TextField(blank=True)),
                ('dp_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_requests', to='cin7.branch')),
                ('dp_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_approvals', to='users.customuser')),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_requests', to='dashboard.salesforecast')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_requests', to='cin7.product')),
                ('store_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_approvals', to='users.customuser')),
            ],
            options={
                'ordering': ['-created_at', '-urgency'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('store_new_request', 'New Replenishment Request (Store Manager)'), ('store_reminder', 'Reminder to Review (Store Manager)'), ('dp_new_batch', 'New Batch for Review (DP Team)'), ('dp_urgent', 'Urgent Stock Alert (DP Team)'), ('po_created', 'PO Created Notification')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchaseorder')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_notifications', to='users.customuser')),
                ('replenishment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.replenishmentrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='replenishment_requests',
            field=models.ManyToManyField(related_name='purchase_orders', to='dashboard.replenishmentrequest'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['request_id'], name='dashboard_r_request_2d5bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['status', 'branch'], name='dashboard_r_status_8beb53_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['week_number', 'year'], name='dashboard_r_week_nu_624dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['urgency', 'status'], name='dashboard_r_urgency_97caf2_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['school_name'], name='dashboard_r_school__0d8bed_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='dashboard_p_po_numb_e620f8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='dashboard_p_status_33b9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier_name'], name='dashboard_p_supplie_ad5a18_idx'),
        ),
    ]
