# Generated by Django 6.0.1 on 2026-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_purchaseorder_replenishmentrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecastBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('statistical', 'Statistical Model'), ('ml', 'Machine Learning'), ('hybrid', 'Hybrid (Statistical + ML)')], default='statistical', max_length=20)),
                ('aggregation_level', models.CharField(choices=[('school', 'By School'), ('product', 'By Product'), ('shop', 'By Shop Location'), ('category', 'By Category')], max_length=20)),
                ('entity_name', models.CharField(db_index=True, max_length=255)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_forecasts', models.JSONField(default=dict)),
                ('forecast_date', models.DateField(db_index=True)),
                ('training_data_start', models.DateField()),
                ('training_data_end', models.DateField()),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('model_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-forecast_date', 'entity_name'],
                'indexes': [models.Index(fields=['forecast_id'], name='dashboard_s_forecas_8f2cbd_idx'), models.Index(fields=['aggregation_level'], name='dashboard_s_aggrega_eebf6c_idx'), models.Index(fields=['entity_name', 'forecast_date'], name='dashboard_s_entity__0b6376_idx'), models.Index(fields=['forecast_date'], name='dashboard_s_forecas_1f561d_idx')],
                'unique_together': {('entity_name', 'aggregation_level', 'forecast_date')},
            },
        ),
    ]
