# Generated by Django 6.0.1 on 2026-03-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_salesforecastbase_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(db_index=True, max_length=255)),
                ('aggregation_level', models.CharField(db_index=True, max_length=20)),
                ('last_generated', models.DateTimeField()),
                ('next_generation_due', models.DateTimeField(db_index=True)),
                ('generation_frequency_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('current', 'Current'), ('due', 'Due for Regeneration'), ('overdue', 'Overdue')], db_index=True, default='current', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_generation_due', 'entity_name'],
                'indexes': [models.Index(fields=['entity_name', 'aggregation_level'], name='dashboard_f_entity__8909a5_idx'), models.Index(fields=['status', 'next_generation_due'], name='dashboard_f_status_781017_idx'), models.Index(fields=['aggregation_level', 'status'], name='dashboard_f_aggrega_ad7c21_idx')],
                'unique_together': {('entity_name', 'aggregation_level')},
            },
        ),
    ]
