# Generated by Django 6.0.1 on 2026-03-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_forecastschedule_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforecastbase',
            name='monthly_demand_30',
            field=models.FloatField(blank=True, help_text='Sum of next 30 days demand (30-60 days from forecast_date)', null=True),
        ),
        migrations.AddField(
            model_name='salesforecastbase',
            name='monthly_demand_60',
            field=models.FloatField(blank=True, help_text='Sum of next 60 days demand (0-60 days from forecast_date)', null=True),
        ),
    ]
