# Generated by Django 6.0.1 on 2026-03-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_monthly_demand_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforecastbase',
            name='growth_metrics',
            field=models.JSONField(default=dict, help_text="Growth trend analysis: {'direction': 'growth', 'annual_rate': 14.5, 'trend_strength': 'moderate', 'last_year_total': 420, 'forecast_year_total': 480}"),
        ),
        migrations.AddField(
            model_name='salesforecastbase',
            name='monthly_breakdown',
            field=models.JSONField(default=dict, help_text="Monthly forecast breakdown: {'2027-01': {'quantity': 59, 'avg_last_3_years': 51.7, 'min': 45, 'max': 58, 'confidence': 'high', 'is_peak_month': True, 'historical_sales': [45, 52, 58]}}"),
        ),
        migrations.AddField(
            model_name='salesforecastbase',
            name='seasonal_profile',
            field=models.JSONField(default=dict, help_text="Seasonal pattern analysis: {'peak_months': [1, 2, 11, 12], 'medium_months': [3, 10], 'low_months': [4, 5, 9], 'zero_months': [6, 7, 8], 'peak_season_label': 'Back-to-School (Jan-Feb)', 'annual_forecast': 450}"),
        ),
    ]
