# Generated by Django 6.0.1 on 2026-03-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_add_simple_forecast_fields'),
        ('users', '0004_customuser_assigned_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforecast',
            name='aggregation_level',
            field=models.CharField(choices=[('school', 'By School'), ('product', 'By Product'), ('shop', 'By Shop Location')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salesforecastbase',
            name='aggregation_level',
            field=models.CharField(choices=[('school', 'By School'), ('product', 'By Product'), ('shop', 'By Shop Location')], max_length=20),
        ),
        migrations.CreateModel(
            name='StoreReplenishmentRequestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('school', models.CharField(db_index=True, max_length=255)),
                ('request_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], db_index=True, default='draft', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_store_requests', to='users.customuser')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_replenishment_batches', to='users.customuser')),
            ],
            options={
                'db_table': 'dashboard_store_replenishment_batch',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreReplenishmentRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_on_hand', models.IntegerField(default=0)),
                ('incoming_stock', models.IntegerField(default=0)),
                ('forecasted_stock', models.IntegerField(default=0)),
                ('stock_gap', models.IntegerField(default=0)),
                ('requested_quantity', models.IntegerField()),
                ('approved_quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('original_quantity', models.IntegerField(blank=True, null=True)),
                ('modification_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.storereplenishmentrequestbatch')),
            ],
            options={
                'db_table': 'dashboard_store_replenishment_item',
                'ordering': ['product_name', 'size'],
            },
        ),
        migrations.AddIndex(
            model_name='storereplenishmentrequestbatch',
            index=models.Index(fields=['request_number'], name='dashboard_s_request_e9bfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='storereplenishmentrequestbatch',
            index=models.Index(fields=['status', 'school'], name='dashboard_s_status_a882b2_idx'),
        ),
        migrations.AddIndex(
            model_name='storereplenishmentrequestbatch',
            index=models.Index(fields=['requested_by', 'status'], name='dashboard_s_request_eb45f9_idx'),
        ),
        migrations.AddIndex(
            model_name='storereplenishmentrequestitem',
            index=models.Index(fields=['batch', 'sku'], name='dashboard_s_batch_i_4b200d_idx'),
        ),
        migrations.AddIndex(
            model_name='storereplenishmentrequestitem',
            index=models.Index(fields=['sku'], name='dashboard_s_sku_68eddc_idx'),
        ),
    ]
