# Generated by Django 6.0.1 on 2026-03-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_salesforecast_aggregation_level_and_more'),
        ('users', '0004_customuser_assigned_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereplenishmentrequestbatch',
            name='dp_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dp_approved_requests', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='storereplenishmentrequestbatch',
            name='dp_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storereplenishmentrequestbatch',
            name='store_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_approved_requests', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='storereplenishmentrequestbatch',
            name='store_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storereplenishmentrequestbatch',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('store_approved', 'Store Approved'), ('dp_approved', 'DP Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], db_index=True, default='submitted', max_length=20),
        ),
    ]
