# Generated by Django 6.0.1 on 2026-03-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_storereplenishmentrequestbatch_dp_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforecastbase',
            name='forecast_valid_until',
            field=models.DateField(blank=True, db_index=True, help_text='Date when this forecast expires (24 months from forecast_date)', null=True),
        ),
    ]
