# Generated by Django 6.0.1 on 2026-03-18 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_forecast_valid_until'),
        ('users', '0006_copy_assigned_branch_to_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPerformingSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(db_index=True, help_text='School name (from sub_category)', max_length=255, unique=True)),
                ('category_name', models.CharField(help_text="Category name (e.g., 'Avondale Shop')", max_length=255)),
                ('is_top_performing', models.BooleanField(db_index=True, default=False, help_text='Mark as top performing school')),
                ('last_fy_sales', models.DecimalField(decimal_places=2, default=0, help_text='Last financial year sales (NZD)', max_digits=12)),
                ('last_fy_start', models.DateField(blank=True, help_text='Financial year start date', null=True)),
                ('last_fy_end', models.DateField(blank=True, help_text='Financial year end date', null=True)),
                ('sales_updated_at', models.DateTimeField(blank=True, help_text='When sales data was last calculated', null=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_top_schools', to='users.customuser')),
            ],
            options={
                'ordering': ['-last_fy_sales', 'school_name'],
                'indexes': [models.Index(fields=['school_name'], name='dashboard_t_school__4615fc_idx'), models.Index(fields=['is_top_performing'], name='dashboard_t_is_top__1dbe9a_idx'), models.Index(fields=['-last_fy_sales'], name='dashboard_t_last_fy_8c0ce6_idx')],
            },
        ),
    ]
