# Generated by Django 6.0.1 on 2026-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSchoolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(db_index=True, help_text="Store/Shop name (extracted from category_name, e.g., 'Penrose Store')", max_length=255)),
                ('school_name', models.CharField(db_index=True, help_text='School name (from sub_category)', max_length=255)),
                ('category_name', models.CharField(help_text="Full category name from products (e.g., 'Penrose Store', 'Mt Albert Shop')", max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this mapping is active')),
                ('product_count', models.IntegerField(default=0, help_text='Number of products in this store-school combination')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['store_name', 'school_name'],
                'indexes': [models.Index(fields=['store_name', 'school_name'], name='dashboard_s_store_n_0803eb_idx'), models.Index(fields=['category_name'], name='dashboard_s_categor_dc64b9_idx'), models.Index(fields=['is_active'], name='dashboard_s_is_acti_bc0ce8_idx')],
                'unique_together': {('category_name', 'school_name')},
            },
        ),
    ]
