# Generated by Django 6.0.1 on 2026-03-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_store_school_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='topperformingschool',
            name='auto_selected',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this school was auto-selected as top 52'),
        ),
        migrations.AddField(
            model_name='topperformingschool',
            name='store_location',
            field=models.CharField(blank=True, help_text='Store/Shop location (extracted from category_name)', max_length=255, null=True),
        ),
    ]
