# Generated by Django 6.0.1 on 2026-03-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_add_auto_selected_and_store_location'),
        ('users', '0007_add_assigned_stores_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityScoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_risk_days', models.IntegerField(default=15, help_text='Days of coverage threshold for Critical Risk (< X days)')),
                ('critical_risk_score', models.IntegerField(default=100, help_text='Score for Critical Risk items')),
                ('high_risk_days', models.IntegerField(default=30, help_text='Days of coverage threshold for High Risk (< X days)')),
                ('high_risk_score', models.IntegerField(default=80, help_text='Score for High Risk items')),
                ('medium_risk_days', models.IntegerField(default=60, help_text='Days of coverage threshold for Medium Risk (< X days)')),
                ('medium_risk_score', models.IntegerField(default=40, help_text='Score for Medium Risk items')),
                ('low_risk_score', models.IntegerField(default=10, help_text='Score for Low Risk items (> medium_risk_days)')),
                ('top_customer_count', models.IntegerField(default=56, help_text='Number of top performing schools/customers to prioritize')),
                ('top_customer_weight', models.IntegerField(default=20, help_text='Additional points for top customers')),
                ('high_velocity_weight', models.IntegerField(default=10, help_text='Additional points for high-velocity items (above category average)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser')),
            ],
            options={
                'verbose_name': 'Priority Score Settings',
                'verbose_name_plural': 'Priority Score Settings',
            },
        ),
    ]
