# Generated by Django 6.0.1 on 2026-03-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_priorityscoresettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforecastbase',
            name='total_quantity_365d',
            field=models.FloatField(blank=True, db_index=True, help_text='Precomputed total forecasted quantity across all days', null=True),
        ),
    ]
